Use EXIT trap to print pass/fail.

diff --git a/test/s b/test/s
--- a/test/s
+++ b/test/s
@@ -1,5 +1,8 @@
 #!/bin/sh
 : ${SED?}
+printf '%s ' "$0"
+trap "printf 'failed\n'" EXIT
+
 
 alias sed="$SED"
 
@@ -44,4 +47,5 @@ case $res in
   (*) exit 6 ;;
 esac
 
-printf '%s passed\n' "$0"
+printf 'passed\n'
+trap '' EXIT
